config/routes.rb
Rails.application.routes.draw do
  
  root 'home#home'  
  get 'home/about'
  get 'home/contact'
  get 'home/fashion'
  get 'home/mechanical'
  get 'home/outsource'
  resources :home

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale
 
	def set_locale
		#I18n.default_locale = :en
		I18n.locale = params[:locale] || I18n.default_locale
	end

	 def default_url_options(options={})
	    { :locale => I18n.locale }
	  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_ads.html.slim
.sub-body.about-section
  h3 
    = t :whychooseus
  .line
    .line-element
  .about-content.container-fluid
    .about-checkbox
      .checkbox-elemtent.container-fluid
        h6 
          = t :staffworking
        i.fa.fa-check-square-o
      .checkbox-elemtent.container-fluid
        h6 
          = t :newideas
        i.fa.fa-check-square-o
      .checkbox-elemtent.container-fluid
        h6
          = t :customer
        i.fa.fa-check-square-o
    .about-video
      .about-bg
        <video width="100%" height="300" controls>
          <source src="https://fbcdn-video-j-a.akamaihd.net/hvideo-ak-xpt1/v/t42.1790-2/12176569_10153755395363307_2112681272_n.mp4?efg=eyJybHIiOjU3NCwicmxhIjo1MTIsInZlbmNvZGVfdGFnIjoic2QifQ%3D%3D&rl=574&vabr=319&oh=d104edd2068289dc7b904258141a69ad&oe=56F7CD70&__gda__=1459085306_0e95fe8c0563d70c9256c294b79fb079" type="video/mp4">
        </video>

app/views/home/_blog.html.slim
.sub-body.blog-section
  h3 
  	= t :blog
  .line
    .line-element
  .blog-content-body.container-fluid
    .blog-element
			= image_tag 'blog01.jpg'
			.blog-content
				h4 Cơ hội thách thức ngành dệt may Việt Nam gia nhập TPP
				p 
					i.fa.fa-calendar
					| 27-01-2016
	.blog-element
			= image_tag 'blog02.jpg'
			.blog-content
				h4 9 trào lưu thời trang cưới phá cách 2016
				p 
					i.fa.fa-calendar
					| 27-01-2016
	.blog-element
			= image_tag 'blog03.jpg'
			.blog-content
				h4 Chào tất cả mọi người!
				p 
					i.fa.fa-calendar
					| 27-01-2016

app/views/home/_image.html.slim
.image-section
  .image-content
    h4 
      = t :outsourcing
    = link_to home_outsource_path do
      button 
        = t :seemore
    end
  .image-content
    h4 
      = t :mechanical
    = link_to home_mechanical_path do
      button 
        = t :seemore
    end
  .image-content
    h4 
      = t :fashion
    = link_to home_fashion_path do
      button 
        = t :seemore 
    end
  .image-bg
    = image_tag ''
    = image_tag ''
    = image_tag ''

app/views/home/_partner.html.slim
.sub-body.partner-section
  h3 
    = t :partner
  .line
    .line-element
  .partner-content-body.container-fluid
  	.partner-element
      = image_tag 'pn1.png'
  	.partner-element
      = image_tag 'pn2.png'
  	.partner-element
      = image_tag 'pn3.png'
  	.partner-element
      = image_tag 'pn4.png'
  	.partner-element.img-large
      = image_tag 'pn5.png'
  	.partner-element.img-large
      = image_tag 'pn6.png'
  	.partner-element.img-large
      = image_tag 'pn7.png' 
  	.partner-element.img-large
      = image_tag 'pn8.png' 
    .partner-element
      = image_tag 'pn9.png'

app/views/home/_slider.html.slim
.sub-body.service-section.container-fluid
	.service-element
		= image_tag 'fashion.png', :class => 'img-fashion'
		.service-content
			h4 
				= t :fashion
			p Gia công áo sơ mi, quần âu nam và áo vest ...
	.service-element
		= image_tag 'process.png'
		.service-content
			h4 
				= t :process
			p Chúng tôi luôn mang đến sản phẩm chất lượng đến KH
	.service-element
		= image_tag 'outsource.png', :class => 'img-outsource'
		.service-content
			h4 
				= t :mechanicalinstall
			p Sản xuất các loại bàn ghế, máy móc, giá để hàng ...

app/views/home/about.html.slim
.sub-body.introduce-section
	ul.link-title
		= link_to root_path do
			li Home
		end
		li 
			| /
		li 
			= t :about
	.introduce-content
		h3 
			= t :about
		p 
			= t :about01
		p 
			= t :about02
		p 
			= t :about03
		p 
			= t :about04
		ul 
			li 
				= t :about05
			li 
				= t :about06
			li 
				= t :about07
			li 
				= t :about08
		p 
			= t :about09
		ul 
			li 
				= t :about10
			li 
				= t :about11
		p 
			= t :about12
		ul 
			li 
				= t :about13
			li 
				= t :about14
			li 
				= t :about15
			li 
				= t :about16
			li 
				= t :about17
			li 
				= t :about18
    p 
    	= t :about19

app/views/home/contact.html.slim
.sub-body.introduce-section
	ul.link-title
		= link_to root_path do
			li 
				= t :home
		end
		li 
			| /
		li 
			= t :contact
	.introduce-content.container-fluid
		h3 
			= t :contact
		.map
			<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script><div style="overflow:hidden;height:500px;width:600px;"><div id="gmap_canvas" style="height:500px;width:600px;"><style>#gmap_canvas img{max-width:none!important;background:none!important}</style><a class="google-map-code" href="http://www.themecircle.net/wordpress-wedding/" id="get-map-data">The Circle</a></div></div><script type="text/javascript"> function init_map(){var myOptions = {zoom:16,center:new google.maps.LatLng(21.0267519,105.84919300000001),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(21.0267519, 105.84919300000001)});infowindow = new google.maps.InfoWindow({content:"<b>The Circle</b><br/>Toong S&#7889; 8 Tr&agrave;ng Thi, Qu&#7853;n Ho&agrave;n Ki&#7871;m, H&agrave; N&#7897;i<br/> Viet Nam" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
		.info-contact
			p 
				i.fa.fa-home
				| Toong Số 8 Tràng Thi, Quận Hoàn Kiếm, Hà Nội
			p 
				i.fa.fa-phone-square
				| +8490 3401 707
			p 
				i.fa.fa-envelope
				| nguyenthoque@hyg.com.vn

app/views/home/fashion.html.slim
.sub-body.introduce-section
	ul.link-title
		= link_to root_path do
			li 
				= t :home
		end
		li 
			| /
		li 
			= t :fashion
	.introduce-content.container-fluid
		h3 
			= t :fashion
		= image_tag 'fashion-bg.jpg'
		.image-element
			= image_tag 'fashion1.png'
			p 
				= t :fashion01
		.image-element
			= image_tag 'fashion2.png', :class => 'img-fashion2'
			p 
				= t :fashion02
		.image-element
			= image_tag 'fashion3.png'
			p 
				= t :fashion03

app/views/home/home.html.slim
= render "image"
= render "slider"
= render "ads"
= render "partner"

app/views/home/outsource.html.slim
.sub-body.introduce-section
	ul.link-title
		= link_to root_path do
			li 
				= t :home
		end
		li 
			| /
		li 
			= t :outsourcing
	.introduce-content.container-fluid
		h3 
			= t :outsourcing
		table
			tr
				th STT
				th Content
				th DVT
				th So luong
				th Don gia (VND)
				th Ghi chu
			tr 
				td 1
			 	td Gía gia công cho 01 mầu sản phẩm (Dài tay)
			 	td Chiếc
			 	td Dưới 30 sản phẩm/01 mầu hoặc 01 quy cách	
				td 110.000	
				td
			tr 
				td 2
			 	td Gía gia công cho 01 mầu sản phẩm (Dài tay)
			 	td Chiếc
			 	td Trên 30 sản phẩm – 50 sản phẩm/01 mầu hoặc 01 quy cách
				td 100.000	
				td
			tr 
				td 3
			 	td Gía gia công cho 01 mầu sản phẩm (Dài tay)
			 	td Chiếc
			 	td Trên 50 sản phẩm – 100 sản phẩm/01 mầu hoặc 01 quy cách
				td 95.000	
				td
			tr 
				td 4
			 	td Gía gia công cho 01 mầu sản phẩm (Dài tay)
			 	td Chiếc
			 	td Trên 100 sản phẩm – 200 sản phẩm/01 mầu hoặc 01 quy cách
				td 85.000
				td
			tr 
				td 5
			 	td Gía gia công cho 01 mầu sản phẩm (Dài tay)
			 	td Chiếc
			 	td Trên 200 sản phẩm – 500 sản phẩm/01 mầu hoặc 01 quy cách
				td 75.000
				td
			tr 
				td 6
			 	td Gía gia công cho 01 mầu sản phẩm (Dài tay)
			 	td Chiếc
			 	td Trên 500 sản phẩm – 1.000 sản phẩm/01 mầu hoặc 01 quy cách
				td 65.000
				td
			tr 
				td 7
			 	td Gía gia công cho 01 mầu sản phẩm (Dài tay)
			 	td Chiếc
			 	td Trên 1.000 sản phẩm/01 mầu hoặc 01 quy cách
				td 55.000
				td

app/views/layouts/_footer.html.slim
.footer-section
  .footer-content
    .footer-element.left
      p 
        i.fa.fa-map-marker
        | Toong Số 8 Tràng Thi, Quận Hoàn Kiếm, Hà Nội
      p 
        i.fa.fa-phone
        | nguyenthoque@hyg.com.vn
      p @ 2016 Copyright - Hai Yen Pte Ld
    ul.footer-element.right
      li
        = link_to root_path do 
          p 
            = t :home
        end
      li
        = link_to home_about_path do 
          p 
           = t :about
        end
      li
        = link_to home_fashion_path do 
          p 
            = t :fashion
        end
      li
        = link_to home_mechanical_path do 
          p 
            = t :mechanical
        end
      li
        = link_to home_outsource_path do 
          p 
            = t :outsourcing
        end
      li
        = link_to home_contact_path do 
          p 
            = t :contact
        end

app/views/layouts/_header.html.slim
.logo
  h1.title-cpd Hai Yen
.navbar
  = image_tag 'icon-bar.png'
ul.menu-content
  li class=("#{'active' if current_page?(root_path)}")
    = link_to root_path do
      = t :home
    end
  li class=("#{'active' if current_page?(home_about_path)}")
    = link_to home_about_path do
      = t :about
    end
  li class=("#{'active' if current_page?(home_fashion_path)}")
    = link_to home_fashion_path do
      = t :fashion
    end
  li class=("#{'active' if current_page?(home_mechanical_path)}")
    = link_to home_mechanical_path do
      = t :mechanical
    end
  li class=("#{'active' if current_page?(home_outsource_path)}")
    = link_to home_outsource_path do
      = t :outsourcing
    end
  li class=("#{'active' if current_page?(home_contact_path)}")
    = link_to home_contact_path do
      = t :contact
    end
  li.locale
    = link_to :locale=>'vi' do
      button 
        = image_tag 'icon-vie.png'
    end
    = link_to :locale=>'en' do
      button 
        = image_tag 'icon-en.png'
    end

app/views/layouts/application.html.slim
doctype html
html
  head
    title - HYG - Thời trang, Gia công cao cấp
    meta name="viewport" content="width=device-width, initial-scale=1"
    link rel="shortcut icon" type="image/x-icon" href="http://megaicons.net/static/img/icons_sizes/367/1039/256/letter-g-black-icon.png"/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags

  body data-spy="scroll"
      
        .header-section.container-fluid
          = render "layouts/header"
        .body-content
          = yield
        .footer-section.container-fluid
          = render "layouts/footer"